### ISSUE TITLE
Whether there exists the [length] token?

### ISSUE THREAD

**Issue by yfzhang114** [facebookresearch/DisCo#11]
I have a question about the length token. I cannot find the length token in the input source sentences
![image](https://user-images.githubusercontent.com/53161950/121763143-34f04480-cb6c-11eb-9e8a-6c174c02fe2a.png)

**Comment by jungokasai** [comment]
I suspect you mean the sentence lengths that the model has to predict to do non-auotregressive generation.
They are not explicitly fed as input to the model because you can just find them by looking at target tokens.
It's happening here: https://github.com/facebookresearch/DisCo/blob/master/fairseq/criterions/label_smoothed_length_cross_entropy.py#L60

**Comment by yfzhang114** [comment]
Thanks for your apply. In the paper, you say

> Againfollowing CMLMs, we append a special token to the encoderand project the vector to predict the target length for paralleldecoding. We add the negative log likelihood loss from thislength prediction to the loss from word predictions

However, I cannot see the special token in the input tokens.

**Comment by jungokasai** [comment]
Oh I misunderstood your question. It's added in the encoder forward pass: 
https://github.com/facebookresearch/DisCo/blob/master/fairseq/models/bert_seq2seq.py#L567
Maybe I should have said "prepend" instead of "append".

**Comment by yfzhang114** [comment]
oh! I see it. Many thx.
